import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};
import type { LayoutProps as NextLayoutProps } from "next/dist/lib/metadata/types"; 
interface LayoutProps extends NextLayoutProps {
  types?: string;
}

interface LayoutProps {
  children: React.ReactNode;
  types?: string; // Optional
}

export default function RootLayout({
  children,
  types,
}: LayoutProps) {
  return (
    <html lang="en">
      <body className={types || ''}>{children}</body>
    </html>
  );
}
