import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
  types,
}: Readonly<{
  children: React.ReactNode;
  types?: string;
}>) {
  return (
    <html lang="en">
      <body className={types || ''}>{children}

      </body>
    </html>
  );
}
